### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by rover886** [coreyauger/AudioLoopbackFilter#2]
I have done desktop screen recording application using DirectShow I want to record system sounds also, will this filter useful to me? How to use this in C# based application, any sample application? will you please provide me DLL of this filter, because I tried to build this project in VS 2013 but faced following error:

```
Error   1   error LNK1181: cannot open input file 'C:\Program Files\Microsoft SDKs\Windows\v7.1\Samples\multimedia\directshow\baseclasses\Release\strmbase.lib' E:\Downloads\AudioLoopbackFilter-master\AudioLoopbackFilter-master\LINK AudioLoopbackFilter

```

**Comment by coreyauger** [comment]
This will compile into a direct show filter that you can use as an `audio source` from any application.  The link error that you are seeing is related to not having the direct show base classes linked into the project.  You should take a read through the documentation here https://msdn.microsoft.com/en-us/library/windows/desktop/dd375456%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

**Comment by rover886** [comment]
Yes, after posting this issue i able to compile the solution and successfully implemented in demo application. Thanks :+1:

**Comment by coreyauger** [comment]
Cool I am glad it is working for you.  Lots of fun things you can do with it :)
